#!/bin/bash

function createHospital() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/hospital.healthnetwork.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-hospital --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospital.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospital.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospital.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-hospital.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy hospital's CA cert to hospital's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/msp/tlscacerts/ca.crt"

  # Copy hospital's CA cert to hospital's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/tlsca/tlsca.hospital.healthnetwork.com-cert.pem"

  # Copy hospital's CA cert to hospital's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/ca"
  cp "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem" "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/ca/ca.hospital.healthnetwork.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-hospital --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/peers/peer0.hospital.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/peers/peer0.hospital.healthnetwork.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/peers/peer0.hospital.healthnetwork.com/tls" --enrollment.profile tls --csr.hosts peer0.hospital.healthnetwork.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/peers/peer0.hospital.healthnetwork.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/peers/peer0.hospital.healthnetwork.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/peers/peer0.hospital.healthnetwork.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/peers/peer0.hospital.healthnetwork.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/peers/peer0.hospital.healthnetwork.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/peers/peer0.hospital.healthnetwork.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/users/User1@hospital.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/users/User1@hospital.healthnetwork.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org1admin:org1adminpw@localhost:7054 --caname ca-hospital -M "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/users/Admin@hospital.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/hospital/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/hospital.healthnetwork.com/users/Admin@hospital.healthnetwork.com/msp/config.yaml"
}

function createPharmacy() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/pharmacy.healthnetwork.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-pharmacy --tls.certfiles "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-pharmacy.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-pharmacy.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-pharmacy.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-pharmacy.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy pharmacy's CA cert to pharmacy's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem" "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/msp/tlscacerts/ca.crt"

  # Copy pharmacy's CA cert to pharmacy's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem" "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/tlsca/tlsca.pharmacy.healthnetwork.com-cert.pem"

  # Copy pharmacy's CA cert to pharmacy's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/ca"
  cp "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem" "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/ca/ca.pharmacy.healthnetwork.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-pharmacy --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-pharmacy --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-pharmacy --id.name org2admin --id.secret org2adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-pharmacy -M "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/peers/peer0.pharmacy.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/peers/peer0.pharmacy.healthnetwork.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-pharmacy -M "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/peers/peer0.pharmacy.healthnetwork.com/tls" --enrollment.profile tls --csr.hosts peer0.pharmacy.healthnetwork.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/peers/peer0.pharmacy.healthnetwork.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/peers/peer0.pharmacy.healthnetwork.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/peers/peer0.pharmacy.healthnetwork.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/peers/peer0.pharmacy.healthnetwork.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/peers/peer0.pharmacy.healthnetwork.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/peers/peer0.pharmacy.healthnetwork.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-pharmacy -M "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/users/User1@pharmacy.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/users/User1@pharmacy.healthnetwork.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org2admin:org2adminpw@localhost:8054 --caname ca-pharmacy -M "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/users/Admin@pharmacy.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/pharmacy/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/pharmacy.healthnetwork.com/users/Admin@pharmacy.healthnetwork.com/msp/config.yaml"
}

function createInsurance() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/insurance.healthnetwork.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-insurance --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-insurance.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-insurance.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-insurance.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-insurance.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy insurance's CA cert to insurance's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/msp/tlscacerts/ca.crt"

  # Copy insurance's CA cert to insurance's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/tlsca/tlsca.insurance.healthnetwork.com-cert.pem"

  # Copy insurance's CA cert to insurance's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/ca"
  cp "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem" "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/ca/ca.insurance.healthnetwork.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-insurance --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-insurance --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-insurance --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-insurance -M "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/peers/peer0.insurance.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/peers/peer0.insurance.healthnetwork.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-insurance -M "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/peers/peer0.insurance.healthnetwork.com/tls" --enrollment.profile tls --csr.hosts peer0.insurance.healthnetwork.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/peers/peer0.insurance.healthnetwork.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/peers/peer0.insurance.healthnetwork.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/peers/peer0.insurance.healthnetwork.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/peers/peer0.insurance.healthnetwork.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/peers/peer0.insurance.healthnetwork.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/peers/peer0.insurance.healthnetwork.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-insurance -M "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/users/User1@insurance.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/users/User1@insurance.healthnetwork.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org1admin:org1adminpw@localhost:11054 --caname ca-insurance -M "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/users/Admin@insurance.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/insurance/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/insurance.healthnetwork.com/users/Admin@insurance.healthnetwork.com/msp/config.yaml"
}

function createLaboratory() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/laboratory.healthnetwork.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-laboratory --tls.certfiles "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-laboratory.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-laboratory.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-laboratory.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-laboratory.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy laboratory's CA cert to laboratory's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem" "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/msp/tlscacerts/ca.crt"

  # Copy laboratory's CA cert to laboratory's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem" "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/tlsca/tlsca.laboratory.healthnetwork.com-cert.pem"

  # Copy laboratory's CA cert to laboratory's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/ca"
  cp "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem" "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/ca/ca.laboratory.healthnetwork.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-laboratory --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-laboratory --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-laboratory --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-laboratory -M "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/peers/peer0.laboratory.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/peers/peer0.laboratory.healthnetwork.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-laboratory -M "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/peers/peer0.laboratory.healthnetwork.com/tls" --enrollment.profile tls --csr.hosts peer0.laboratory.healthnetwork.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/peers/peer0.laboratory.healthnetwork.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/peers/peer0.laboratory.healthnetwork.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/peers/peer0.laboratory.healthnetwork.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/peers/peer0.laboratory.healthnetwork.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/peers/peer0.laboratory.healthnetwork.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/peers/peer0.laboratory.healthnetwork.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-laboratory -M "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/users/User1@laboratory.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/users/User1@laboratory.healthnetwork.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org1admin:org1adminpw@localhost:10054 --caname ca-laboratory -M "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/users/Admin@laboratory.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/laboratory/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/laboratory.healthnetwork.com/users/Admin@laboratory.healthnetwork.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/healthnetwork.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/healthnetwork.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/healthnetwork.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/healthnetwork.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/healthnetwork.com/msp/tlscacerts/tlsca.healthnetwork.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/healthnetwork.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/healthnetwork.com/tlsca/tlsca.healthnetwork.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/healthnetwork.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/tls" --enrollment.profile tls --csr.hosts orderer.healthnetwork.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/healthnetwork.com/orderers/orderer.healthnetwork.com/msp/tlscacerts/tlsca.healthnetwork.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/healthnetwork.com/users/Admin@healthnetwork.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/healthnetwork.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/healthnetwork.com/users/Admin@healthnetwork.com/msp/config.yaml"
}


createHospital
createPharmacy
createInsurance
createLaboratory
createOrderer

